def display_menu():
    print("Please choose an option:")
    print("  1. Add Expense")
    print("  2. View Expenses")
    print("  3. View Expenses by Category")
    print("  4. Add Income")
    print("  5. View Income")
    print("  6. View Income by Category")
    print("  7. Set Budget for a Category")
    print("  8. View Budget for a Category")
    print("  9. Set Financial Goals")
    print(" 10. View Progress Towards Financial Goals")
    print(" 11. Generate Dashboard")
    print(" 12. Export Data")
    print(" 13. Quit")
    print("\n")
